# Generated by Django 3.1.2 on 2020-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0007_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_orders',
            field=models.IntegerField(default=0),
        ),
    ]
