# Generated by Django 3.1.2 on 2020-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0009_listing_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_path',
            new_name='image_path_l',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_path_s',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
